language: objective-c
env: 
- AUDIOKIT_CI=1 LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install: gem install xcpretty cocoapods -N
script:
- set -o pipefail && xcodebuild test -scheme OSXObjectiveCAudioKitTests
  -project Tests/TestProjects/OSXObjectiveCAudioKit/OSXObjectiveCAudioKit.xcodeproj | xcpretty -c
- pod lib lint --quick AudioKit.podspec.json
