language: objective-c
osx_image: beta-xcode6.3

env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8

before_install: gem install xcpretty cocoapods -N
podfile: Playgrounds/AudioKitPlayground/Podfile
cache: cocoapods
script: ./Tests/travis.sh
