language: objective-c
env:
- AUDIOKIT_CI=1 LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install: gem install xcpretty cocoapods -N
script:
- pod install --project-directory=Playgrounds/AudioKitPlayground
- set -o pipefail && xcodebuild -workspace Playgrounds/AudioKitPlayground/AudioKitPlayground.xcworkspace 
  -scheme AudioKitPlayground -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- set -o pipefail && xcodebuild -scheme OSXObjectiveCAudioKitTests
  -project Tests/TestProjects/OSXObjectiveCAudioKit/OSXObjectiveCAudioKit.xcodeproj test | xcpretty -c
- pod lib lint --quick AudioKit.podspec.json
